import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import "@fortawesome/fontawesome-free/css/all.min.css";
import "react-image-gallery/styles/css/image-gallery.css";
import NavBar from "@/components/NavBar/NavBar";
import { Toaster } from "react-hot-toast";
import Providers from "@/components/Provider/Providers";
import ReduxHydrator from "@/components/Provider/ReduxHydrator";
import ClientOnly from "@/components/ClientOnly/ClientOnly";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased`}
      >
        <Providers>
        <ClientOnly><NavBar /></ClientOnly>
        <div className="container min-h-[65vh] pb-10 pt-20 mx-auto ">
          <ReduxHydrator />
        {children}
        </div>
        </Providers>
        <Toaster />
      </body>
    </html>
  );
}
